name: DashGaussian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=12.6
  - plyfile
  - python=3.10.18
  - pip=22.3.1
  - pytorch=2.7.0
  - torchvision=0.22.0
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - submodules/lanczos-resampling
    - opencv-python
    - joblib
    - lpips
    - laspy
    - jaxtyping
    - torch_scatter
    - debugpy
    # - numpy==1.25.0
    - wheel
    - tqdm
    - lightning
    - black
    - ruff
    - hydra-core
    - jaxtyping
    - beartype
    - colorama
    - scikit-image
    - colorspacious
    - matplotlib
    - moviepy==1.0.3
    - imageio
    - timm
    - DateTime
    - imgaug
    - iopath
    - imagecorruptions
    - mmcv
    - tensorboardX
    - HTML4Vision
    - dacite
    - lpips
    - e3nn
    - plyfile
    - tabulate
    - svg.py
    - scikit-video
    - Pillow
    - huggingface_hub
    - gradio
    - xformers==0.0.30
    - pydantic
    - open3d==0.19.0
    - einops
    - safetensors
