name: DashGaussian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=12.6
  - plyfile
  - python=3.10.18
  - pip=22.3.1
  - pytorch=2.7.0
  - torchvision=0.22.0
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - submodules/lanczos-resampling
    - opencv-python
    - joblib
    - lpips
    - laspy
    - einops
    - jaxtyping
    - torch_scatter
